apiVersion: apps/v1
kind: Deployment
metadata:
  name: mineru-server
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "mineru-server.annotations" . | nindent 4 }}
  labels:
    {{- include "mineru-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mineru-server
  template:
    metadata:
      labels:
        app: mineru-server
    spec:
      {{- if .Values.runtimeClassName }}
      runtimeClassName: {{ .Values.runtimeClassName | quote }}
      {{- end }}
      containers:
      - name: mineru-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          {{- if and .Values.config .Values.config.enable }}
          - name: config-volume
            mountPath: /root/magic-pdf.json
            subPath: magic-pdf.json
          - name: models-volume
            mountPath: {{ .Values.config.models_dir | quote }}
          - name: layoutreader-model-volume
            mountPath: {{ .Values.config.layoutreader_model_dir | quote }}
          {{- end }}
          - mountPath: /tmp
            name: host-tmp
        ports:
        - containerPort: 8300
        env:
        - name: MAX_WORKER
          value: {{ .Values.max_worker | default "1" }}
        - name: MAX_TASK_SIZE
          value: {{ .Values.max_task_size | default "1" }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if and .Values.config .Values.config.enable }}
        - name: config-volume
          configMap:
            name: mineru-config
        - name: models-volume
          hostPath:
            path: {{ .Values.config.models_dir }}
            type: Directory
        - name: layoutreader-model-volume
          hostPath:
            path: {{ .Values.config.layoutreader_model_dir }}
            type: Directory
        {{- end }}
        - hostPath:
            path: /tmp
            type: Directory
          name: host-tmp